const getters = {
  isMobile: state => state.app.isMobile,
  lang: state => state.app.lang,
  theme: state => state.app.theme,
  color: state => state.app.color,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  nickname: state => state.user.name,
  welcome: state => state.user.welcome,
  roles: state => state.user.roles,
  userInfo: state => state.user.info,
  siteDomain: state => state.syssettings.siteDomain,
  apiKey: state => state.syssettings.apiKey,
  regStatus: state => state.syssettings.regStatus,
  emailStatus: state => state.syssettings.emailStatus,
  emailSuffix: state => state.syssettings.emailSuffix,
  defaultQuota: state => state.syssettings.defaultQuota,
  sEmailStatus: state => state.syssettings.sEmailStatus,
  sEmailName: state => state.syssettings.sEmailName,
  sEmailData: state => state.syssettings.sEmailData,
  sLdapStatus: state => state.syssettings.sLdapStatus,
  sLdapName: state => state.syssettings.sLdapName,
  sLdapData: state => state.syssettings.sLdapData,
  sDingtaskStatus: state => state.syssettings.sDingtaskStatus,
  sDingtaskName: state => state.syssettings.sDingtaskName,
  sDingtaskData: state => state.syssettings.sDingtaskData,
  quotainfo: state => state.user.quotainfo,
  addRouters: state => state.permission.addRouters,
  multiTab: state => state.app.multiTab
}

export default getters
